name: Update Lowlighter Metrics

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Lowlighter Metrics svg
        run: |
          curl -s https://lowlighter.vercel.app/api/stars/NexarObs?border=true -o github-metrics.svg

      - name: Update README
        run: |
         if grep -q "NexarObs Starred Topics" README.md; then
         sed -i 's|!\[NexarObs Starred Topics\](.*)|![NexarObs Starred Topics](github-metrics.svg)|' README.md
         else
          echo "\n## Tech Stack (Starred Topics)\n\n![NexarObs Starred Topics](github-metrics.svg)" >> README.md
         fi

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md assets/lowlighter_metrics.png
          git commit -m "Update Lowlighter metrics" || echo "No changes to commit"
          git push
